[theme]
primaryColor = "#f0f018"  # Deep Green
backgroundColor = "#160852"  # Dark Blue
secondaryBackgroundColor = "#140436"  # Slightly lighter Blue
textColor = "#F5E8C7"  # Off-white Yellowish
font = "serif"
